---
title: "LandCover EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(sp)
library(rgdal)
library(sf)
library(ggplot2)
library(dplyr)
library(reshape2)
```


```{r}
#function for reading land cover data
read_land_cover <- function(directory){
  return(raster(directory))
}

#Jessica
jessica_tif <- "C:\\Users\\jeske\\Desktop\\capstone\\data\\tcma_classnames_updated\\TCMA_ClassNames_Updated\\tcma_lc_finalv1.tif.tif"
land_cover <- read_land_cover(jessica_tif)

getwd()

# Ann
ann_tif <- "C:\\Users\\amuud\\OneDrive\\Desktop\\capstone data\\tcma_lc_finalv1.tif"

#Serene
serene_tif <- "/Users/serenelee/Capstone/TCMA_ClassNames_Updated/tcma_lc_finalv1.tif"
land_cover <- read_land_cover(serene_tif)

# This is Julia's changes

```


```{r}
#function for reading land use data
read_land_use <- function(directory){
  return(st_read(directory))
}

#Jessica respective directories
jessica_sf <- "C:\\Users\\jeske\\Desktop\\capstone\\data\\shp_plan_generl_lnduse_historical\\GeneralizedLandUseHistorical.shp"
land_use <- read_land_use(jessica_sf)
#Ann

#Serene
serene_sf <- "/Users/serenelee/Capstone/shp_plan_generl_lnduse_historical/GeneralizedLandUseHistorical.shp"
land_use <- read_land_use(serene_sf)

ann_sf <- "C:\\Users\\amuud\\OneDrive\\Desktop\\land use data\\GeneralizedLandUseHistorical.shp"

#can call in console
#land_use <- read_land_use(jessica_sf)
```

```{r}
potential_forest <- land_use %>% 
  filter(Dscrpt2016 == "Park, Recreational, or Preserve" |
           Dscrpt2016 == "Undeveloped")

```

```{r}
landuse_percentages <- landuse_filtered %>% 
  rename(type = DSCRPT2016, `NA` = VALUE_0, `Grass/Shrub` = VALUE_1, `Bare Soil` = VALUE_2, Buildings= VALUE_3, `Roads/Paved Surfaces` = VALUE_4, `Lakes/Ponds` = VALUE_5, `Deciduous Tree Canopy` = VALUE_6, `Coniferous Tree Canopy` = VALUE_7, Agriculture = VALUE_8, `Emergent Wetland` = VALUE_9, `Forested/Shrub Wetland` = VALUE_10, River = VALUE_11, Extraction = VALUE_12) %>% 
  melt(id.vars = c("type", "OBJECTID")) %>% 
  mutate(percent = case_when(
    type == "Park, Recreational, or Preserve" ~ (value/747410768)*100,
    type == "Undeveloped" ~ (value/1702916156)*100
  ))

#to get sums per type:

# landuse_percentages %>% 
#   group_by(type) %>% 
#   summarize(sum(value))

#total park etc: 747410768
#total undeveloped: 1702916156


colnames(landuse_filtered)
```
"1" = "Grass/Shrub",
                       "2" = "Bare Soil",
                       "3" = "Buildings",
                       "4" = "Roads/Paved Surfaces",
                       "5" = "Lakes/Ponds",
                       "6" = "Deciduous Tree Canopy",
                       "7" = "Coniferous Tree Canopy",
                       "8" = "Agriculture",
                       "9" = "Emergent Wetland",
                       "10" = "Forested/Shrub Wetland",
                       "11" = "River",
                       "12" = "Extraction"))
