---
title: "Serene-Julia-Cropping"
author: "Bouzaher, Julia"
date: "April 23, 2020"
output: html_document
---

```{r}
library(data.table)
library(sf)
library(sp)
library(raster)
library(dplyr)
library(rgdal)
library(rgeos)

# extent(landcover)
# e <- as(extent(460000, 465000, 4980000, 4990000), 'SpatialPolygons')
# 
# crs(landcover)
# crs(e) <- "+proj=utm +zone=15 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
# crs(e)
# cropped2 <- raster::crop(landcover,e)
# plot(cropped2, axes = TRUE)

xmax <- 521239.5
ymax <- 5029162
xrange <-  521239.5 - 419971.5 
yrange <- 5029162 -  4924218
firsty <- yrange/2

xcroprange <- 5000
ycroprange <- 4990000 - 4980000
yincrement <- yrange/3
xincrement <- xrange/10

e <- as(extent(460000, 465000, 4980000, 4990000), 'SpatialPolygons')

y1 <- c(4924218, 4924218+yincrement)
y2 <- c(4924218+yincrement, 4924218+2*yincrement)
y3 <- c(4924218+2*yincrement, 5029162)

x1 <- c(xmax - xincrement, xmax)
x2 <- c(xmax - 2*xincrement, xmax - xincrement)
x3 <- c(xmax - 3*xincrement, xmax - 2*xincrement)
x4 <- c(xmax - 4*xincrement, xmax - 3*xincrement)
x5 <- c(xmax - 5*xincrement, xmax - 4*xincrement)
x6 <- c(xmax - 6*xincrement, xmax - 5*xincrement)
x7 <- c(xmax - 7*xincrement, xmax - 6*xincrement)
x8 <- c(xmax - 8*xincrement, xmax - 7*xincrement)
x9 <- c(xmax - 9*xincrement, xmax - 8*xincrement)
x10 <- c(xmax - 10*xincrement, xmax - 9*xincrement)

#we want to split x into 10 and y into 3 fto obtain 30 blocks total
#xmin, xmax, ymin, ymax

crop1 <- as(extent(x1,y1), 'SpatialPolygons')
crop2 <- as(extent(x2,y1), 'SpatialPolygons')
crop3 <- as(extent(x3,y1), 'SpatialPolygons')
crop4 <- as(extent(x4,y1), 'SpatialPolygons')
crop5 <- as(extent(x5,y1), 'SpatialPolygons')
crop6 <- as(extent(x6,y1), 'SpatialPolygons')
crop7 <- as(extent(x7,y1), 'SpatialPolygons')
crop8 <- as(extent(x8,y1), 'SpatialPolygons')
crop9 <- as(extent(x9,y1), 'SpatialPolygons')
crop10 <- as(extent(x10,y1), 'SpatialPolygons')
crop11 <- as(extent(x1,y2), 'SpatialPolygons')
crop12 <- as(extent(x2,y2), 'SpatialPolygons')
crop13 <- as(extent(x3,y2), 'SpatialPolygons')
crop14 <- as(extent(x4,y2), 'SpatialPolygons')
crop15 <- as(extent(x5,y2), 'SpatialPolygons')
crop16 <- as(extent(x6,y2), 'SpatialPolygons')
crop17 <- as(extent(x7,y2), 'SpatialPolygons')
crop18 <- as(extent(x8,y2), 'SpatialPolygons')
crop19 <- as(extent(x9,y2), 'SpatialPolygons')
crop20 <- as(extent(x10,y2), 'SpatialPolygons')
crop21 <- as(extent(x1,y3), 'SpatialPolygons')
crop22 <- as(extent(x2,y3), 'SpatialPolygons')
crop23 <- as(extent(x3,y3), 'SpatialPolygons')
crop24 <- as(extent(x4,y3), 'SpatialPolygons')
crop25 <- as(extent(x5,y3), 'SpatialPolygons')
crop26 <- as(extent(x6,y3), 'SpatialPolygons')
crop27 <- as(extent(x7,y3), 'SpatialPolygons')
crop28 <- as(extent(x8,y3), 'SpatialPolygons')
crop29 <- as(extent(x9,y3), 'SpatialPolygons')
crop30 <- as(extent(x10,y3), 'SpatialPolygons')

```



```{r}

#actually cropping the dataframe with the bounds created above


land1 <- raster::crop(landcover,crop1)
land2 <- raster::crop(landcover,crop2)
land3 <- raster::crop(landcover,crop3)
land4 <- raster::crop(landcover,crop4)

land5 <- raster::crop(landcover,crop5)
land6 <- raster::crop(landcover,crop6)

land7 <- raster::crop(landcover,crop7)
land8 <- raster::crop(landcover,crop8)
land9 <- raster::crop(landcover,crop9)
land10 <- raster::crop(landcover,crop10)
land11 <- raster::crop(landcover,crop11)
land12 <- raster::crop(landcover,crop12)

land13 <- raster::crop(landcover,crop13)
land14 <- raster::crop(landcover,crop14)
land15 <- raster::crop(landcover,crop15)
land16 <- raster::crop(landcover,crop16)
land17 <- raster::crop(landcover,crop17)
land18 <- raster::crop(landcover,crop18)
land19 <- raster::crop(landcover,crop19)
land20 <- raster::crop(landcover,crop20)
land21 <- raster::crop(landcover,crop21)
land22 <- raster::crop(landcover,crop22)

land23 <- raster::crop(landcover,crop23)
land24 <- raster::crop(landcover,crop24)
land25 <- raster::crop(landcover,crop25)
```

```{r}
land26 <- raster::crop(landcover,crop26)
land27 <- raster::crop(landcover,crop27)
land28 <- raster::crop(landcover,crop28)
land29 <- raster::crop(landcover,crop29)
land30 <- raster::crop(landcover,crop30)

```

```{r}

tile1 <- raster::as.data.frame(land1, xy = TRUE)
remove(land1)
remove(data)
tile2 <- raster::as.data.frame(land2, xy = TRUE)
tile3 <- raster::as.data.frame(land3, xy = TRUE)
tile4 <- raster::as.data.frame(land4, xy = TRUE)
tile5 <- raster::as.data.frame(land5, xy = TRUE)
tile6 <- raster::as.data.frame(land6, xy = TRUE)
tile7 <- raster::as.data.frame(land7, xy = TRUE)
tile8 <- raster::as.data.frame(land8, xy = TRUE)
tile9 <- raster::as.data.frame(land9, xy = TRUE)
tile10 <- raster::as.data.frame(land10, xy = TRUE)
tile11 <- raster::as.data.frame(land11, xy = TRUE)
tile12 <- raster::as.data.frame(land12, xy = TRUE)
tile13 <- raster::as.data.frame(land13, xy = TRUE)
tile14 <- raster::as.data.frame(land14, xy = TRUE)
tile15 <- raster::as.data.frame(land15, xy = TRUE)
tile16 <- raster::as.data.frame(land16, xy = TRUE)
tile17 <- raster::as.data.frame(land17, xy = TRUE)
tile18 <- raster::as.data.frame(land18, xy = TRUE)
tile19 <- raster::as.data.frame(land19, xy = TRUE)
tile20 <- raster::as.data.frame(land20, xy = TRUE)
tile21 <- raster::as.data.frame(land21, xy = TRUE)
tile22 <- raster::as.data.frame(land22, xy = TRUE)
tile23 <- raster::as.data.frame(land23, xy = TRUE)
tile24 <- raster::as.data.frame(land24, xy = TRUE)
tile25 <- raster::as.data.frame(land25, xy = TRUE)
tile26 <- raster::as.data.frame(land26, xy = TRUE)
tile27 <- raster::as.data.frame(land27, xy = TRUE)
tile28 <- raster::as.data.frame(land28, xy = TRUE)
tile29 <- raster::as.data.frame(land29, xy = TRUE)
tile30 <- raster::as.data.frame(land30, xy = TRUE)


memory.limit(size = 100000000)
memory.size(max = NA)


```


```{r}

#let's try this again

land1 <- raster::raster("land1.tif", RAT = TRUE)
tile1 <- raster::as.data.frame(land1, xy = TRUE)
remove(land1)
fwrite(tile1, "tile1.txt")
remove(tile1)

land2 <- raster::raster("land2.tif", RAT = TRUE)
tile2 <- raster::as.data.frame(land2, xy = TRUE)
remove(land2)
fwrite(tile2, "tile2.txt")
remove(tile2)

land3 <- raster::raster("land3.tif", RAT = TRUE)
tile3 <- raster::as.data.frame(land3, xy = TRUE)
remove(land3)
fwrite(tile3, "tile3.txt")
remove(tile3)

land4 <- raster::raster("land4.tif", RAT = TRUE)
tile4 <- raster::as.data.frame(land4, xy = TRUE)
remove(land4)
fwrite(tile4, "tile4.txt")
remove(tile4)
```

```{r}

land5 <- raster::raster("land5.tif", RAT = TRUE)
tile5 <- raster::as.data.frame(land5, xy = TRUE)
remove(land5)
fwrite(tile5, "tile5.txt")
remove(tile5)

land6 <- raster::raster("land6.tif", RAT = TRUE)
tile6 <- raster::as.data.frame(land6, xy = TRUE)
remove(land6)
fwrite(tile6, "tile6.txt")
remove(tile6)

land7 <- raster::raster("land7.tif", RAT = TRUE)
tile7 <- raster::as.data.frame(land7, xy = TRUE)
remove(land7)
fwrite(tile7, "tile7.txt")
remove(tile7)
```

```{r}

land8 <- raster::raster("land8.tif", RAT = TRUE)
tile8 <- raster::as.data.frame(land8, xy = TRUE)
remove(land8)
fwrite(tile8, "tile8.txt")
remove(tile8)

land9 <- raster::raster("land9.tif", RAT = TRUE)
tile9 <- raster::as.data.frame(land9, xy = TRUE)
remove(land9)
fwrite(tile9, "tile9.txt")
remove(tile9)

```

```{r}
land10 <- raster::raster("land10.tif", RAT = TRUE)
tile10 <- raster::as.data.frame(land10, xy = TRUE)
remove(land10)
fwrite(tile10, "tile10.txt")
remove(tile10)

land11 <- raster::raster("land11.tif", RAT = TRUE)
tile11 <- raster::as.data.frame(land11, xy = TRUE)
remove(land11)
fwrite(tile11, "tile11.txt")
remove(tile11)

land12 <- raster::raster("land12.tif", RAT = TRUE)
tile12 <- raster::as.data.frame(land12, xy = TRUE)
remove(land12)
fwrite(tile12, "tile12.txt")
remove(tile12)


land13 <- raster::raster("land13.tif", RAT = TRUE)
tile13 <- raster::as.data.frame(land13, xy = TRUE)
remove(land13)
fwrite(tile13, "tile13.txt")
remove(tile13)

land14 <- raster::raster("land14.tif", RAT = TRUE)
tile14 <- raster::as.data.frame(land14, xy = TRUE)
remove(land14)
fwrite(tile14, "tile14.txt")
remove(tile14)

land15 <- raster::raster("land15.tif", RAT = TRUE)
tile15 <- raster::as.data.frame(land15, xy = TRUE)
remove(land15)
fwrite(tile15, "tile15.txt")
remove(tile15)

land16 <- raster::raster("land16.tif", RAT = TRUE)
tile16 <- raster::as.data.frame(land16, xy = TRUE)
remove(land16)
fwrite(tile16, "tile16.txt")
remove(tile16)

land17 <- raster::raster("land17.tif", RAT = TRUE)
tile17 <- raster::as.data.frame(land17, xy = TRUE)
remove(land17)
fwrite(tile17, "tile17.txt")
remove(tile17)

land18 <- raster::raster("land18.tif", RAT = TRUE)
tile18 <- raster::as.data.frame(land18, xy = TRUE)
remove(land18)
fwrite(tile18, "tile18.txt")
remove(tile18)

land19 <- raster::raster("land19.tif", RAT = TRUE)
tile19 <- raster::as.data.frame(land19, xy = TRUE)
remove(land19)
fwrite(tile19, "tile19.txt")
remove(tile19)

land20 <- raster::raster("land20.tif", RAT = TRUE)
tile20 <- raster::as.data.frame(land20, xy = TRUE)
remove(land20)
fwrite(tile20, "tile20.txt")
remove(tile20)


land21 <- raster::raster("land21.tif", RAT = TRUE)
tile21 <- raster::as.data.frame(land21, xy = TRUE)
remove(land21)
fwrite(tile21, "tile21.txt")
remove(tile21)

land22 <- raster::raster("land22.tif", RAT = TRUE)
tile22 <- raster::as.data.frame(land22, xy = TRUE)
remove(land22)
fwrite(tile22, "tile22.txt")
remove(tile22)


land23 <- raster::raster("land23.tif", RAT = TRUE)
tile23 <- raster::as.data.frame(land23, xy = TRUE)
remove(land23)
fwrite(tile23, "tile23.txt")
remove(tile23)

land24 <- raster::raster("land24.tif", RAT = TRUE)
tile24 <- raster::as.data.frame(land24, xy = TRUE)
remove(land24)
fwrite(tile24, "tile24.txt")
remove(tile24)

land25 <- raster::raster("land25.tif", RAT = TRUE)
tile25 <- raster::as.data.frame(land25, xy = TRUE)
remove(land25)
fwrite(tile25, "tile25.txt")
remove(tile25)

land26 <- raster::raster("land26.tif", RAT = TRUE)
tile26 <- raster::as.data.frame(land26, xy = TRUE)
remove(land26)
fwrite(tile26, "tile26.txt")
remove(tile26)

land27 <- raster::raster("land27.tif", RAT = TRUE)
tile27 <- raster::as.data.frame(land27, xy = TRUE)
remove(land27)
fwrite(tile27, "tile27.txt")
remove(tile27)

land28 <- raster::raster("land28.tif", RAT = TRUE)
tile28 <- raster::as.data.frame(land28, xy = TRUE)
remove(land28)
fwrite(tile28, "tile28.txt")
remove(tile28)


land29 <- raster::raster("land29.tif", RAT = TRUE)
tile29 <- raster::as.data.frame(land29, xy = TRUE)
remove(land29)
fwrite(tile29, "tile29.txt")
remove(tile29)

land30 <- raster::raster("land30.tif", RAT = TRUE)
tile30 <- raster::as.data.frame(land30, xy = TRUE)
remove(land30)
fwrite(tile30, "tile30.txt")
remove(tile30)



```


```{r}
land4 <- raster::raster("land4.tif", RAT = TRUE)
land5 <- raster::raster("land5.tif", RAT = TRUE)
land6 <- raster::raster("land6.tif", RAT = TRUE)
land7 <- raster::raster("land7.tif", RAT = TRUE)
land8 <- raster::raster("land8.tif", RAT = TRUE)
land9 <- raster::raster("land9.tif", RAT = TRUE)
land10 <- raster::raster("land10.tif", RAT = TRUE)
land11 <- raster::raster("land11.tif", RAT = TRUE)
land12 <- raster::raster("land12.tif", RAT = TRUE)
land13 <- raster::raster("land13.tif", RAT = TRUE)
land14 <- raster::raster("land14.tif", RAT = TRUE)
land15 <- raster::raster("land15.tif", RAT = TRUE)
land16 <- raster::raster("land16.tif", RAT = TRUE)
land17 <- raster::raster("land17.tif", RAT = TRUE)
land18 <- raster::raster("land18.tif", RAT = TRUE)
land19 <- raster::raster("land19.tif", RAT = TRUE)
land20 <- raster::raster("land20.tif", RAT = TRUE)
land21 <- raster::raster("land21.tif", RAT = TRUE)
land22 <- raster::raster("land22.tif", RAT = TRUE)
land23 <- raster::raster("land23.tif", RAT = TRUE)
land24 <- raster::raster("land24.tif", RAT = TRUE)
land25 <- raster::raster("land25.tif", RAT = TRUE)
land26 <- raster::raster("land26.tif", RAT = TRUE)
land27 <- raster::raster("land27.tif", RAT = TRUE)
land28 <- raster::raster("land28.tif", RAT = TRUE)
land29 <- raster::raster("land29.tif", RAT = TRUE)
land30 <- raster::raster("land30.tif", RAT = TRUE)


```


Comments on merging 30 dataframes and calculating the percentages for each region:
```{r}
# Merging all 30 files: could possibly use rbind() on .txt and .csv files because all tables have the same variable names
# ie. Combinedtiles <- rbind(tile1, tile2, tile3,..., tile30)
# should result in a datafram called 'Combinedtiles' with ~1.5e+09 observations

#Delete the pixel information for memory management. Omitt 'x' and 'y' columns and keep only the 'tcma_lc_finalv1' column
# ie. Combinedtiles %>%
#          select(tcma_lc_finalv1)

# Calculating percentages for each category:
# Combinedtiles %>%
#  group_by("tcma_lc_finalv1") %>%
#  summarize(count = n()) %>% --> should result in a summary count for each category

#Combinedtiles %>%
#  mutate(totalCount = sum(count),
#         Percent = count/totalCount) --> should result in the percentage for each category
  




```










